cellsociety_team02: Cell.SharkCell Class Reference
Cell.SharkCell Class Reference
Public Member Functions
SharkCell (double state, int x, int y, Map< String, String > parameters)
SharkCell (SharkCell sharkCell, int chronons, int hunger)
Paint getColor ()
void updateStateandMove (Patch[][] patches)
Public Member Functions inherited from Cell.PredPreyCell
PredPreyCell (double state, int x, int y, Map< String, String > parameters)
PredPreyCell (PredPreyCell c)
void updateStateandMove (Patch[][] patches)
Cell makeCell ()
Paint getColor ()
Public Member Functions inherited from Cell.Cell
Cell (double state, int x, int y, Map< String, String > parameters)
Cell (Cell c)
double getCurrentState ()
void setCurrentState (double state)
double getFutureState ()
void setFutureState (double state)
int getFutureX ()
int getFutureY ()
Map< String, String > getParameters ()
abstract void updateStateandMove (Patch[][] patches)
abstract Paint getColor ()
Protected Member Functions
void breed (Patch[][] patches)
void initialize ()
Protected Member Functions inherited from Cell.PredPreyCell
Patch pickMove (List< Patch > moves)
void checkBreed (Patch[][] patches)
void breed (Patch[][] patches)
void setDeltas ()
void initialize ()
Protected Member Functions inherited from Cell.Cell
double errorCheck (String string, double result)
abstract void setDeltas ()
abstract void initialize ()
List< Patch > getNeighbors (Patch[][] patches)
Private Attributes
int starve
int myHunger
Static Private Attributes
static final int DEFAULT_STARVE = 4
static final int DEFAULT_SHARKBREED = 5
Additional Inherited Members
Static Public Attributes inherited from Cell.PredPreyCell
static final double WATER = 0
static final double FISH = 1
static final double SHARK = 2
static final int INITIAL_CHRONONS = 0
static final int INITIAL_HUNGER = 0
Protected Attributes inherited from Cell.PredPreyCell
int myChronons
int myBreed
Protected Attributes inherited from Cell.Cell
double currentState
double futureState
int currentX
int currentY
int futureX
int futureY
int[] xDelta
int[] yDelta
Map< String, String > myParameters
String boundaryType
Detailed Description
Author
Greg Lyons
Kevin Rhine
Chase Malik
Subclass of PredPreyCell, implemented to use shark behavior in the simulation
Definition at line 21 of file SharkCell.java.
Constructor & Destructor Documentation
Cell.SharkCell.SharkCell (double state, int x, int y, Map< String, String > parameters)
Definition at line 28 of file SharkCell.java.
References Cell.PredPreyCell.INITIAL_CHRONONS, Cell.PredPreyCell.INITIAL_HUNGER, and Cell.PredPreyCell.myChronons.
Referenced by Cell.SharkCell.breed(), and Cell.SharkCell.updateStateandMove().
Cell.SharkCell.SharkCell (SharkCell sharkCell, int chronons, int hunger)
Definition at line 34 of file SharkCell.java.
References Cell.PredPreyCell.myChronons.
Member Function Documentation
void Cell.SharkCell.breed (Patch patches[][]) protected
Definition at line 91 of file SharkCell.java.
References Cell.Cell.currentX, Cell.Cell.currentY, Cell.Cell.myParameters, Patch.Patch.setFutureCell(), Cell.PredPreyCell.SHARK, and Cell.SharkCell.SharkCell().
Paint Cell.SharkCell.getColor ()
Definition at line 42 of file SharkCell.java.
void Cell.SharkCell.initialize () protected
Definition at line 96 of file SharkCell.java.
References Cell.Cell.errorCheck(), and Cell.PredPreyCell.myBreed.
void Cell.SharkCell.updateStateandMove (Patch patches[][])
Updating is similar to fish Sharks prioritize eating fish over an empty water location Sharks can overwrite the move of a fish trying to escape in the same round Sharks also have a hunger factor that increases if they don't eat, and they eventually starve
Parameters
patches
Definition at line 54 of file SharkCell.java.
References Cell.PredPreyCell.checkBreed(), Cell.Cell.currentX, Cell.Cell.currentY, Cell.PredPreyCell.FISH, Cell.FishCell.food(), Patch.Patch.getCurrentCell(), Patch.Patch.getCurrentX(), Patch.Patch.getCurrentY(), Cell.Cell.getNeighbors(), Cell.FishCell.getNewMove(), Cell.PredPreyCell.INITIAL_HUNGER, Cell.PredPreyCell.myChronons, Cell.Cell.myParameters, Cell.PredPreyCell.pickMove(), Cell.PredPreyCell.PredPreyCell(), Patch.Patch.setFutureCell(), Cell.PredPreyCell.SHARK, Cell.SharkCell.SharkCell(), and Cell.PredPreyCell.WATER.
Member Data Documentation
final int Cell.SharkCell.DEFAULT_SHARKBREED = 5 static private
Definition at line 24 of file SharkCell.java.
final int Cell.SharkCell.DEFAULT_STARVE = 4 static private
Definition at line 23 of file SharkCell.java.
int Cell.SharkCell.myHunger private
Definition at line 26 of file SharkCell.java.
int Cell.SharkCell.starve private
Definition at line 25 of file SharkCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/Cell/SharkCell.java