cellsociety_team02: Cell.SugarCell Class Reference
Cell.SugarCell Class Reference
Public Member Functions
SugarCell (double state, int x, int y, Map< String, String > parameters)
SugarCell (SugarCell c, int sugar)
void updateStateandMove (Patch[][] patches)
Paint getColor ()
Public Member Functions inherited from Cell.Cell
Cell (double state, int x, int y, Map< String, String > parameters)
Cell (Cell c)
double getCurrentState ()
void setCurrentState (double state)
double getFutureState ()
void setFutureState (double state)
int getFutureX ()
int getFutureY ()
Map< String, String > getParameters ()
abstract void updateStateandMove (Patch[][] patches)
abstract Paint getColor ()
Protected Member Functions
void setDeltas ()
void initialize ()
Protected Member Functions inherited from Cell.Cell
double errorCheck (String string, double result)
abstract void setDeltas ()
abstract void initialize ()
List< Patch > getNeighbors (Patch[][] patches)
Private Member Functions
Patch findHighestSugar (List< Patch > neighborPatches)
void move (Patch newLocation, Patch[][] patches)
void assignDeltas (int start, int x, int y)
Private Attributes
int mySugar
int myMetabolism
int myVision
Static Private Attributes
static final double DEFAULT_SUGAR = 5
static final double DEFAULT_VISION = 2
static final double DEFAULT_METABOLISM = 2
static final int alive = 1
static final int dead = 0
Additional Inherited Members
Protected Attributes inherited from Cell.Cell
double currentState
double futureState
int currentX
int currentY
int futureX
int futureY
int[] xDelta
int[] yDelta
Map< String, String > myParameters
String boundaryType
Detailed Description
Definition at line 11 of file SugarCell.java.
Constructor & Destructor Documentation
Cell.SugarCell.SugarCell (double state, int x, int y, Map< String, String > parameters)
Definition at line 23 of file SugarCell.java.
Referenced by Cell.SugarCell.move().
Cell.SugarCell.SugarCell (SugarCell c, int sugar)
Definition at line 27 of file SugarCell.java.
Member Function Documentation
void Cell.SugarCell.assignDeltas (int start, int x, int y) private
Definition at line 100 of file SugarCell.java.
References Cell.SugarCell.myVision, Cell.Cell.xDelta, and Cell.Cell.yDelta.
Referenced by Cell.SugarCell.setDeltas().
Patch Cell.SugarCell.findHighestSugar (List< Patch > neighborPatches) private
Finds the patch with the highest sugar that it can move to Loops through the list of patches it can see and finds the one with the highest sugar value that does not have a cell in the future If multiple patches have the same high sugar, it choose the closest one
Parameters
List<Patch> list of neighboring patches of the cell
Returns
Patch patch with the highest sugar that the cell can move to
Definition at line 47 of file SugarCell.java.
References Cell.Cell.currentX, Cell.Cell.currentY, Cell.SugarCell.dead, Cell.Cell.futureX, Cell.Cell.futureY, Patch.Patch.getCurrentState(), Patch.Patch.getCurrentX(), and Patch.Patch.getCurrentY().
Referenced by Cell.SugarCell.updateStateandMove().
Paint Cell.SugarCell.getColor ()
Definition at line 107 of file SugarCell.java.
References Cell.Cell.currentState.
void Cell.SugarCell.initialize () protected
Definition at line 113 of file SugarCell.java.
References Cell.Cell.errorCheck().
void Cell.SugarCell.move (Patch newLocation, Patch patches[][]) private
Moves the current cell to the patch it is given The cell takes the sugar from the new patch and updates its own sugar After subtracting its own metabolism, if the cell still has sugar it sets the new location's future cell to this cell and sets the current patch's future cell to a dead cell If it ran out of sugar then it instead sets the new location's future cell to a dead cell
Parameters
patch newLocation destination for the current cell
Patch[][] patches array of all patches on the grid
Definition at line 81 of file SugarCell.java.
References Cell.Cell.currentX, Cell.Cell.currentY, Cell.Cell.futureX, Cell.Cell.futureY, Patch.Patch.getCurrentState(), Cell.SugarCell.myMetabolism, Cell.Cell.myParameters, Patch.Patch.setFutureCell(), Patch.Patch.setFutureState(), and Cell.SugarCell.SugarCell().
Referenced by Cell.SugarCell.updateStateandMove().
void Cell.SugarCell.setDeltas () protected
Definition at line 91 of file SugarCell.java.
References Cell.SugarCell.assignDeltas(), Cell.Cell.xDelta, and Cell.Cell.yDelta.
void Cell.SugarCell.updateStateandMove (Patch patches[][])
Definition at line 32 of file SugarCell.java.
References Cell.Cell.currentState, Cell.SugarCell.findHighestSugar(), Cell.Cell.getNeighbors(), and Cell.SugarCell.move().
Member Data Documentation
final int Cell.SugarCell.alive = 1 static private
Definition at line 16 of file SugarCell.java.
final int Cell.SugarCell.dead = 0 static private
Definition at line 17 of file SugarCell.java.
Referenced by Cell.SugarCell.findHighestSugar().
final double Cell.SugarCell.DEFAULT_METABOLISM = 2 static private
Definition at line 15 of file SugarCell.java.
final double Cell.SugarCell.DEFAULT_SUGAR = 5 static private
Definition at line 13 of file SugarCell.java.
final double Cell.SugarCell.DEFAULT_VISION = 2 static private
Definition at line 14 of file SugarCell.java.
int Cell.SugarCell.myMetabolism private
Definition at line 19 of file SugarCell.java.
Referenced by Cell.SugarCell.move().
int Cell.SugarCell.mySugar private
Definition at line 18 of file SugarCell.java.
int Cell.SugarCell.myVision private
Definition at line 20 of file SugarCell.java.
Referenced by Cell.SugarCell.assignDeltas().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/Cell/SugarCell.java