cellsociety_team02: cellsociety_team02.XMLParser Class Reference
cellsociety_team02.XMLParser Class Reference
Public Member Functions
XMLParser (File f)
void initialize ()
Map< String, String > makeParameterMap ()
Cell[][] makeCells ()
Patch[][] makePatches ()
String getGridType ()
int getNumStates ()
Private Member Functions
String getAttribute (Node n, String s)
Map< String, String > makeMap (String s)
void constructList (String s)
void doGiven (String s)
void doRandom (String s)
void doProbability (String s)
void setNullState ()
Private Attributes
Document myDoc
String myType
String myConfig
Cell[][] cellsList
Patch[][] patchesList
int maxRow
int maxCol
Map< String, String > paramMap
int myNumStates
int myNumPatches
Factory factory
String myGridType
Static Private Attributes
static final int DEFAULT_PATCH_VALUE = 1
static final int DEFAULT_CELL_VALUE = 0
Detailed Description
Retrieves information from XML files designed for CA simulations Stores the information in relevant data structures
Author
Chase Malik
Greg Lyons
Kevin Rhine
Definition at line 24 of file XMLParser.java.
Constructor & Destructor Documentation
cellsociety_team02.XMLParser.XMLParser (File f)
Takes an xml file and creates a document that can be parsed
Parameters
f XML file with CA data
Definition at line 45 of file XMLParser.java.
Member Function Documentation
void cellsociety_team02.XMLParser.constructList (String s) private
Using the xml input, creates an array of states for either cells or patches Based on the model's configuration
Parameters
s String that defines whether to create array for cells or patches
Definition at line 141 of file XMLParser.java.
References cellsociety_team02.XMLParser.doGiven(), cellsociety_team02.XMLParser.doProbability(), and cellsociety_team02.XMLParser.doRandom().
Referenced by cellsociety_team02.XMLParser.makeCells(), and cellsociety_team02.XMLParser.makePatches().
void cellsociety_team02.XMLParser.doGiven (String s) private
Using the xml input, creates an array of states for either cells or patches Looks for all the nodes of the type s Creates the appropriate cell or patch at the location given Then sets all null entries equal to a cell or patch with its default value
Parameters
s String that defines whether to create cells or patches
Definition at line 156 of file XMLParser.java.
References cellsociety_team02.XMLParser.getAttribute(), cellsociety_team02.Factory.makeCell(), cellsociety_team02.Factory.makePatch(), and cellsociety_team02.XMLParser.setNullState().
Referenced by cellsociety_team02.XMLParser.constructList().
void cellsociety_team02.XMLParser.doProbability (String s) private
Using the xml input, creates an array of states for either cells or patches Creates a map of cell probabilities and patch probabilities Loops through all possible locations and creates a cell or patch at the location based on the map
Parameters
s String that defines whether to create cells or patches
Definition at line 192 of file XMLParser.java.
References cellsociety_team02.XMLParser.makeMap(), cellsociety_team02.Factory.makeProbCell(), and cellsociety_team02.Factory.makeProbPatch().
Referenced by cellsociety_team02.XMLParser.constructList().
void cellsociety_team02.XMLParser.doRandom (String s) private
Using the xml input, creates an array of states for either cells or patches Loops through all possible locations and creates a random cell or patch at the location
Parameters
s String that defines whether to create cells or patches
Definition at line 177 of file XMLParser.java.
References cellsociety_team02.Factory.makeRandomCell(), and cellsociety_team02.Factory.makeRandomPatch().
Referenced by cellsociety_team02.XMLParser.constructList().
String cellsociety_team02.XMLParser.getAttribute (Node n, String s) private
Gets the value of the attribute associated with the node and string
Parameters
n Node in the xml file
s String representing the attribute of interest
Returns
String representing the value associated with attribute s
Definition at line 89 of file XMLParser.java.
Referenced by cellsociety_team02.XMLParser.doGiven(), cellsociety_team02.XMLParser.initialize(), and cellsociety_team02.XMLParser.makeMap().
String cellsociety_team02.XMLParser.getGridType ()
Return the type of grid
Returns
String of grid type
Definition at line 228 of file XMLParser.java.
References cellsociety_team02.XMLParser.myGridType.
Referenced by cellsociety_team02.GridModel.load().
int cellsociety_team02.XMLParser.getNumStates ()
Return the maximum number of cell states
Returns
int myNumStates
Definition at line 236 of file XMLParser.java.
References cellsociety_team02.XMLParser.myNumStates.
Referenced by cellsociety_team02.GridModel.load().
void cellsociety_team02.XMLParser.initialize ()
Gets the important parameters for the simulation Initializes the arrays of cells and patches Makes the parameter map
Definition at line 64 of file XMLParser.java.
References cellsociety_team02.XMLParser.getAttribute(), cellsociety_team02.XMLParser.makeParameterMap(), cellsociety_team02.XMLParser.maxCol, and cellsociety_team02.XMLParser.maxRow.
Referenced by cellsociety_team02.GridModel.load().
Cell [][] cellsociety_team02.XMLParser.makeCells ()
Using the xml input, creates an array of cells
Returns
Cell[][] array of cells
Definition at line 122 of file XMLParser.java.
References cellsociety_team02.XMLParser.cellsList, and cellsociety_team02.XMLParser.constructList().
Referenced by cellsociety_team02.GridModel.load().
Map<String, String> cellsociety_team02.XMLParser.makeMap (String s) private
Makes a map from the xml file based on the string it is passed to their value
Parameters
String s of node name to search for in the xml
Returns
Map<String,String> with keys defined by the s name and value equal to its value
Definition at line 106 of file XMLParser.java.
References cellsociety_team02.XMLParser.getAttribute().
Referenced by cellsociety_team02.XMLParser.doProbability(), and cellsociety_team02.XMLParser.makeParameterMap().
Map<String,String> cellsociety_team02.XMLParser.makeParameterMap ()
Makes a map from parameters in the xml file to their value
Returns
Map<String,String> with keys defined by the xml parameter name and value equal to its value
Definition at line 97 of file XMLParser.java.
References cellsociety_team02.XMLParser.makeMap().
Referenced by cellsociety_team02.XMLParser.initialize().
Patch [][] cellsociety_team02.XMLParser.makePatches ()
Using the xml input, creates an array of patches
Returns
Patch[][] array of patches
Definition at line 131 of file XMLParser.java.
References cellsociety_team02.XMLParser.constructList(), and cellsociety_team02.XMLParser.patchesList.
Referenced by cellsociety_team02.GridModel.load().
void cellsociety_team02.XMLParser.setNullState () private
Sets all null entries in cellsList and patchesList equal to a cell or patch's default state, respectively
Definition at line 212 of file XMLParser.java.
References cellsociety_team02.Factory.makeCell(), and cellsociety_team02.Factory.makePatch().
Referenced by cellsociety_team02.XMLParser.doGiven().
Member Data Documentation
Cell [][] cellsociety_team02.XMLParser.cellsList private
Definition at line 30 of file XMLParser.java.
Referenced by cellsociety_team02.XMLParser.makeCells().
final int cellsociety_team02.XMLParser.DEFAULT_CELL_VALUE = 0 static private
Definition at line 26 of file XMLParser.java.
final int cellsociety_team02.XMLParser.DEFAULT_PATCH_VALUE = 1 static private
Definition at line 25 of file XMLParser.java.
Factory cellsociety_team02.XMLParser.factory private
Definition at line 37 of file XMLParser.java.
int cellsociety_team02.XMLParser.maxCol private
Definition at line 33 of file XMLParser.java.
Referenced by cellsociety_team02.XMLParser.initialize().
int cellsociety_team02.XMLParser.maxRow private
Definition at line 32 of file XMLParser.java.
Referenced by cellsociety_team02.XMLParser.initialize().
String cellsociety_team02.XMLParser.myConfig private
Definition at line 29 of file XMLParser.java.
Document cellsociety_team02.XMLParser.myDoc private
Definition at line 27 of file XMLParser.java.
String cellsociety_team02.XMLParser.myGridType private
Definition at line 38 of file XMLParser.java.
Referenced by cellsociety_team02.XMLParser.getGridType().
int cellsociety_team02.XMLParser.myNumPatches private
Definition at line 36 of file XMLParser.java.
int cellsociety_team02.XMLParser.myNumStates private
Definition at line 35 of file XMLParser.java.
Referenced by cellsociety_team02.XMLParser.getNumStates().
String cellsociety_team02.XMLParser.myType private
Definition at line 28 of file XMLParser.java.
Map<String,String> cellsociety_team02.XMLParser.paramMap private
Definition at line 34 of file XMLParser.java.
Patch [][] cellsociety_team02.XMLParser.patchesList private
Definition at line 31 of file XMLParser.java.
Referenced by cellsociety_team02.XMLParser.makePatches().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/cellsociety_team02/XMLParser.java