cellsociety_team02: Cell.PredPreyCell Class Reference
Cell.PredPreyCell Class Reference
Public Member Functions
PredPreyCell (double state, int x, int y, Map< String, String > parameters)
PredPreyCell (PredPreyCell c)
void updateStateandMove (Patch[][] patches)
Cell makeCell ()
Paint getColor ()
Public Member Functions inherited from Cell.Cell
Cell (double state, int x, int y, Map< String, String > parameters)
Cell (Cell c)
double getCurrentState ()
void setCurrentState (double state)
double getFutureState ()
void setFutureState (double state)
int getFutureX ()
int getFutureY ()
Map< String, String > getParameters ()
abstract void updateStateandMove (Patch[][] patches)
abstract Paint getColor ()
Static Public Attributes
static final double WATER = 0
static final double FISH = 1
static final double SHARK = 2
static final int INITIAL_CHRONONS = 0
static final int INITIAL_HUNGER = 0
Protected Member Functions
Patch pickMove (List< Patch > moves)
void checkBreed (Patch[][] patches)
void breed (Patch[][] patches)
void setDeltas ()
void initialize ()
Protected Member Functions inherited from Cell.Cell
double errorCheck (String string, double result)
abstract void setDeltas ()
abstract void initialize ()
List< Patch > getNeighbors (Patch[][] patches)
Protected Attributes
int myChronons
int myBreed
Protected Attributes inherited from Cell.Cell
double currentState
double futureState
int currentX
int currentY
int futureX
int futureY
int[] xDelta
int[] yDelta
Map< String, String > myParameters
String boundaryType
Detailed Description
Author
Greg Lyons
Chase Malik
Kevin Rhine
PredPreyCell serves as a default cell for the Wa-Tor simulation (representing water cells) It also serves as a super-class for FishCell and SharkCell, which have similar behavior
Some of the methods, like breed() and updateStateandMove(), are empty, because water does not need to breed or update. FishCell and SharkCell override these methods.
The makeCell() method serves as a sort of mini-factory, which is used within the larger Factory class
Definition at line 26 of file PredPreyCell.java.
Constructor & Destructor Documentation
Cell.PredPreyCell.PredPreyCell (double state, int x, int y, Map< String, String > parameters)
Definition at line 36 of file PredPreyCell.java.
Referenced by Cell.PredPreyCell.checkBreed(), Cell.PredPreyCell.makeCell(), and Cell.SharkCell.updateStateandMove().
Cell.PredPreyCell.PredPreyCell (PredPreyCell c)
Definition at line 40 of file PredPreyCell.java.
Member Function Documentation
void Cell.PredPreyCell.breed (Patch patches[][]) protected
Empty for water cells, but will be overridden by subclasses Called from within checkBreed
Parameters
patches
Definition at line 89 of file PredPreyCell.java.
Referenced by Cell.PredPreyCell.checkBreed().
void Cell.PredPreyCell.checkBreed (Patch patches[][]) protected
Checks to see if it is time for the Cell to breed If it is, call its breed method to create a Cell of the correct type
Parameters
patches
Definition at line 72 of file PredPreyCell.java.
References Cell.PredPreyCell.breed(), Cell.Cell.currentX, Cell.Cell.currentY, Cell.PredPreyCell.INITIAL_CHRONONS, Cell.Cell.myParameters, Cell.PredPreyCell.PredPreyCell(), and Patch.Patch.setFutureCell().
Referenced by Cell.SharkCell.updateStateandMove(), and Cell.FishCell.updateStateandMove().
Paint Cell.PredPreyCell.getColor ()
Definition at line 113 of file PredPreyCell.java.
void Cell.PredPreyCell.initialize () protected
Definition at line 118 of file PredPreyCell.java.
References Cell.PredPreyCell.INITIAL_CHRONONS.
Cell Cell.PredPreyCell.makeCell ()
Used as a mini-factory to make cells of the correct type in the larger Factory This makes it easier to be less specific in the larger Factory
Definition at line 97 of file PredPreyCell.java.
References Cell.Cell.currentState, Cell.Cell.currentX, Cell.Cell.currentY, Cell.Cell.myParameters, and Cell.PredPreyCell.PredPreyCell().
Referenced by cellsociety_team02.Factory.makeCell().
Patch Cell.PredPreyCell.pickMove (List< Patch > moves) protected
Picks a random move from a list of possible moves (not simply neighbors)
Parameters
moves
Definition at line 58 of file PredPreyCell.java.
References Cell.Cell.futureX, Cell.Cell.futureY, Patch.Patch.getCurrentX(), and Patch.Patch.getCurrentY().
Referenced by Cell.SharkCell.updateStateandMove(), and Cell.FishCell.updateStateandMove().
void Cell.PredPreyCell.setDeltas () protected
Definition at line 107 of file PredPreyCell.java.
References Cell.Cell.xDelta, and Cell.Cell.yDelta.
void Cell.PredPreyCell.updateStateandMove (Patch patches[][])
Empty for water cells, but will be overridden by subclasses
Definition at line 48 of file PredPreyCell.java.
References Cell.Cell.currentState.
Member Data Documentation
final double Cell.PredPreyCell.FISH = 1 static
Definition at line 29 of file PredPreyCell.java.
Referenced by Cell.SharkCell.updateStateandMove().
final int Cell.PredPreyCell.INITIAL_CHRONONS = 0 static
Definition at line 31 of file PredPreyCell.java.
Referenced by Cell.FishCell.breed(), Cell.PredPreyCell.checkBreed(), Cell.PredPreyCell.initialize(), and Cell.SharkCell.SharkCell().
final int Cell.PredPreyCell.INITIAL_HUNGER = 0 static
Definition at line 32 of file PredPreyCell.java.
Referenced by Cell.SharkCell.SharkCell(), and Cell.SharkCell.updateStateandMove().
int Cell.PredPreyCell.myBreed protected
Definition at line 34 of file PredPreyCell.java.
Referenced by Cell.SharkCell.initialize(), and Cell.FishCell.initialize().
int Cell.PredPreyCell.myChronons protected
Definition at line 33 of file PredPreyCell.java.
Referenced by Cell.FishCell.FishCell(), Cell.SharkCell.SharkCell(), Cell.SharkCell.updateStateandMove(), and Cell.FishCell.updateStateandMove().
final double Cell.PredPreyCell.SHARK = 2 static
Definition at line 30 of file PredPreyCell.java.
Referenced by Cell.SharkCell.breed(), and Cell.SharkCell.updateStateandMove().
final double Cell.PredPreyCell.WATER = 0 static
Definition at line 28 of file PredPreyCell.java.
Referenced by Cell.SharkCell.updateStateandMove(), and Cell.FishCell.updateStateandMove().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/Cell/PredPreyCell.java