cellsociety_team02: cellsociety_team02.GridModel Class Reference
cellsociety_team02.GridModel Class Reference
Public Member Functions
void load ()
void update ()
Patch[][] getPatches ()
String getGridType ()
void changeState (double x, double y)
Map< Integer, XYChart.Series > addData (int newX)
Private Member Functions
XMLParser loadFileToParser ()
void updatePatchesAndCells ()
void setCurrentToFuture ()
void initSeries ()
int numState (int state)
Private Attributes
Cell[][] myCells
Patch[][] myPatches
String myGridType
int myNumStates
Map< Integer, XYChart.Series > seriesMap
Detailed Description
Model for the grid Loads the grid Updates the states of the cells and patches on the grid Stores data for the view to access
Author
Chase Malik
Greg Lyons
Kevin Rhine
Definition at line 23 of file GridModel.java.
Member Function Documentation
Map<Integer,XYChart.Series> cellsociety_team02.GridModel.addData (int newX)
Updates the map from cell state to its data series by adding the new data points
Parameters
int newX data point to be added (number of frames)
Returns
Map updated map
Definition at line 130 of file GridModel.java.
References cellsociety_team02.GridModel.numState(), and cellsociety_team02.GridModel.seriesMap.
Referenced by cellsociety_team02.GridView.makeGraph().
void cellsociety_team02.GridModel.changeState (double x, double y)
Changes the cell's state by one Used for user interaction
Parameters
double x row in the array of the cell to change
double y column in the array of the cell to change
Definition at line 109 of file GridModel.java.
References Patch.Patch.getCurrentCell(), Cell.Cell.getCurrentState(), Cell.Cell.setCurrentState(), and Cell.Cell.setFutureState().
String cellsociety_team02.GridModel.getGridType ()
Returns the type of grid used in this simulation
Returns
String of the grid type
Definition at line 99 of file GridModel.java.
References cellsociety_team02.GridModel.myGridType.
Referenced by cellsociety_team02.GridView.load().
Patch [][] cellsociety_team02.GridModel.getPatches ()
Returns the patches in the grid
Returns
Patch[][] array of all the patches on the grid
Definition at line 91 of file GridModel.java.
References cellsociety_team02.GridModel.myPatches.
Referenced by cellsociety_team02.GridView.makeGrid().
void cellsociety_team02.GridModel.initSeries () private
Creates the appropriate number of series for the graph
Definition at line 119 of file GridModel.java.
References cellsociety_team02.GridModel.myNumStates, and cellsociety_team02.GridModel.seriesMap.
Referenced by cellsociety_team02.GridModel.load().
void cellsociety_team02.GridModel.load ()
loads the file into the xml parser Then initializes the xml parser and gets the cells, patches, gridType, and number of cell states from it It also initializes the series for the graph
Definition at line 48 of file GridModel.java.
References cellsociety_team02.XMLParser.getGridType(), cellsociety_team02.XMLParser.getNumStates(), cellsociety_team02.XMLParser.initialize(), cellsociety_team02.GridModel.initSeries(), cellsociety_team02.GridModel.loadFileToParser(), cellsociety_team02.XMLParser.makeCells(), cellsociety_team02.XMLParser.makePatches(), and cellsociety_team02.GridModel.seriesMap.
Referenced by cellsociety_team02.GridView.load().
XMLParser cellsociety_team02.GridModel.loadFileToParser () private
load the file into the xml parser Prompts the user for an xml file Then passes the chosen file to the XMLParser and returns the XMLParser
Returns
XMLParser parser that can access the chosen file
Definition at line 35 of file GridModel.java.
Referenced by cellsociety_team02.GridModel.load().
int cellsociety_team02.GridModel.numState (int state) private
Counts how many cells of a particular state are on the board and returns the count
Parameters
int state - the state of interest
Returns
int count of the state on the board currently
Definition at line 142 of file GridModel.java.
References Patch.Patch.getCurrentCell(), and Cell.Cell.getCurrentState().
Referenced by cellsociety_team02.GridModel.addData().
void cellsociety_team02.GridModel.setCurrentToFuture () private
Loops through all of the patches to set its currentCell equal to its futureCell
Definition at line 79 of file GridModel.java.
References Patch.Patch.currentToFuture().
Referenced by cellsociety_team02.GridModel.update().
void cellsociety_team02.GridModel.update ()
Updates the patches and cells in the grid Once complete, it ticks forward by setting the current values to all of their future values
Definition at line 62 of file GridModel.java.
References cellsociety_team02.GridModel.setCurrentToFuture(), and cellsociety_team02.GridModel.updatePatchesAndCells().
Referenced by cellsociety_team02.GridView.step().
void cellsociety_team02.GridModel.updatePatchesAndCells () private
Loops through all of the patches to update all of the cells and patches in the grid
Definition at line 69 of file GridModel.java.
References Patch.Patch.updateState().
Referenced by cellsociety_team02.GridModel.update().
Member Data Documentation
Cell [][] cellsociety_team02.GridModel.myCells private
Definition at line 24 of file GridModel.java.
String cellsociety_team02.GridModel.myGridType private
Definition at line 26 of file GridModel.java.
Referenced by cellsociety_team02.GridModel.getGridType().
int cellsociety_team02.GridModel.myNumStates private
Definition at line 27 of file GridModel.java.
Referenced by cellsociety_team02.GridModel.initSeries().
Patch [][] cellsociety_team02.GridModel.myPatches private
Definition at line 25 of file GridModel.java.
Referenced by cellsociety_team02.GridModel.getPatches().
Map<Integer, XYChart.Series> cellsociety_team02.GridModel.seriesMap private
Definition at line 28 of file GridModel.java.
Referenced by cellsociety_team02.GridModel.addData(), cellsociety_team02.GridModel.initSeries(), and cellsociety_team02.GridModel.load().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/cellsociety_team02/GridModel.java