cellsociety_team02: Cell.Cell Class Reference
Cell.Cell Class Reference abstract
Public Member Functions
Cell (double state, int x, int y, Map< String, String > parameters)
Cell (Cell c)
double getCurrentState ()
void setCurrentState (double state)
double getFutureState ()
void setFutureState (double state)
int getFutureX ()
int getFutureY ()
Map< String, String > getParameters ()
abstract void updateStateandMove (Patch[][] patches)
abstract Paint getColor ()
Protected Member Functions
double errorCheck (String string, double result)
abstract void setDeltas ()
abstract void initialize ()
List< Patch > getNeighbors (Patch[][] patches)
Protected Attributes
double currentState
double futureState
int currentX
int currentY
int futureX
int futureY
int[] xDelta
int[] yDelta
Map< String, String > myParameters
String boundaryType
Detailed Description
Abstract Cell Class Stores the information of the cell Updates and moves throughout the grid based on individual simulation rules
Author
Chase Malik
Greg Lyons
Kevin Rhine
Definition at line 19 of file Cell.java.
Constructor & Destructor Documentation
Cell.Cell.Cell (double state, int x, int y, Map< String, String > parameters)
Cell constructor
Parameters
double state Takes the given state and sets the cell's current and future state
int x Takes the given value and sets the cell's current and future x
int y Takes the given value and sets the cell's current and future y
parameters Takes the given value and sets the cell's parameter map
Definition at line 39 of file Cell.java.
Cell.Cell.Cell (Cell c)
Cell constructor
Parameters
Cell c makes a new cell based on the cell c's future values
Definition at line 58 of file Cell.java.
References Cell.Cell.getFutureState(), Cell.Cell.getFutureX(), Cell.Cell.getFutureY(), and Cell.Cell.getParameters().
Member Function Documentation
double Cell.Cell.errorCheck (String string, double result) protected
Return double value of parameter being queried
Parameters
String string representing the parameter being looked up in the parameter map
double default value of the parameter if it isn't in the map
Returns
double value to be used for the parameter in question
Definition at line 125 of file Cell.java.
Referenced by Cell.FireCell.initialize(), Cell.SegregationCell.initialize(), Cell.SharkCell.initialize(), Cell.FishCell.initialize(), and Cell.SugarCell.initialize().
abstract Paint Cell.Cell.getColor () abstract
Abstract method that sets the color of the cell based on the possible states
Referenced by Patch.GenericPatch.getColor(), and cellsociety_team02.GridView.getLocationColor().
double Cell.Cell.getCurrentState ()
Return currentState of cell
Returns
double currentState
Definition at line 66 of file Cell.java.
Referenced by cellsociety_team02.GridModel.changeState(), Cell.SegregationCell.move(), cellsociety_team02.GridModel.numState(), and Patch.FirePatch.updateState().
double Cell.Cell.getFutureState ()
Return futureState of cell
Returns
double futureState
Definition at line 83 of file Cell.java.
Referenced by Cell.Cell.Cell().
int Cell.Cell.getFutureX ()
Return future x position of cell
Returns
double futureX
Definition at line 99 of file Cell.java.
Referenced by Cell.Cell.Cell().
int Cell.Cell.getFutureY ()
Return future y position of cell
Returns
double futureY
Definition at line 107 of file Cell.java.
Referenced by Cell.Cell.Cell().
List<Patch> Cell.Cell.getNeighbors (Patch patches[][]) protected
Method that gets the neighboring patches of the current cell Can use either the finite or the toroidal definition of neighbors
Parameters
Patch[][] patches array of the patches on the board
Returns
List<Patch> list of neighboring patches
Definition at line 159 of file Cell.java.
Referenced by Cell.LifeCell.updateStateandMove(), Cell.FireCell.updateStateandMove(), Cell.SegregationCell.updateStateandMove(), Cell.SugarCell.updateStateandMove(), Cell.SharkCell.updateStateandMove(), and Cell.FishCell.updateStateandMove().
Map<String, String> Cell.Cell.getParameters ()
Return parameters associated with the cell
Returns
Map<String,String> myParameters
Definition at line 115 of file Cell.java.
Referenced by Cell.Cell.Cell().
abstract void Cell.Cell.initialize () abstract protected
Abstract method that sets the initial values of parameters and other information in the cell Varies for each simulation, as they all have different parameters that need to be initialized
void Cell.Cell.setCurrentState (double state)
Set currentState of cell Used for changing colors
Parameters
double sets the cell's current state
Definition at line 75 of file Cell.java.
Referenced by cellsociety_team02.GridModel.changeState().
abstract void Cell.Cell.setDeltas () abstract protected
Abstract method that sets the delta values when checking neighbors Varies for each simulation, as some require four neighbors, while others look at eight
void Cell.Cell.setFutureState (double state)
Set futureState of cell
Parameters
double sets the cell's future state
Definition at line 91 of file Cell.java.
Referenced by cellsociety_team02.GridModel.changeState().
abstract void Cell.Cell.updateStateandMove (Patch patches[][]) abstract
Abstract method that updates the state of the cell and moves it to a new location based on the simulation's logic
Implements the simulation's logic to find its future State Then based on this state, it will either move or stay put
Parameters
Patch[][] patches an array of the patches on the board
Referenced by Patch.GenericPatch.updateState(), Patch.FirePatch.updateState(), and Patch.SugarPatch.updateState().
Member Data Documentation
String Cell.Cell.boundaryType protected
Definition at line 30 of file Cell.java.
double Cell.Cell.currentState protected
Definition at line 21 of file Cell.java.
Referenced by Cell.FireCell.getColor(), Cell.SugarCell.getColor(), Cell.PredPreyCell.makeCell(), Cell.LifeCell.updateStateandMove(), Cell.FireCell.updateStateandMove(), Cell.SegregationCell.updateStateandMove(), Cell.SugarCell.updateStateandMove(), and Cell.PredPreyCell.updateStateandMove().
int Cell.Cell.currentX protected
Definition at line 23 of file Cell.java.
Referenced by Cell.SharkCell.breed(), Cell.FishCell.breed(), Cell.PredPreyCell.checkBreed(), Cell.SugarCell.findHighestSugar(), Cell.PredPreyCell.makeCell(), Cell.SegregationCell.move(), Cell.SugarCell.move(), Cell.LifeCell.updateStateandMove(), Cell.FireCell.updateStateandMove(), and Cell.SharkCell.updateStateandMove().
int Cell.Cell.currentY protected
Definition at line 24 of file Cell.java.
Referenced by Cell.SharkCell.breed(), Cell.FishCell.breed(), Cell.PredPreyCell.checkBreed(), Cell.SugarCell.findHighestSugar(), Cell.PredPreyCell.makeCell(), Cell.SegregationCell.move(), Cell.SugarCell.move(), Cell.LifeCell.updateStateandMove(), Cell.FireCell.updateStateandMove(), and Cell.SharkCell.updateStateandMove().
double Cell.Cell.futureState protected
Definition at line 22 of file Cell.java.
Referenced by Cell.LifeCell.getColor(), Cell.SegregationCell.getColor(), Cell.LifeCell.updateStateandMove(), Cell.FireCell.updateStateandMove(), and Cell.SegregationCell.updateStateandMove().
int Cell.Cell.futureX protected
Definition at line 25 of file Cell.java.
Referenced by Cell.SugarCell.findHighestSugar(), Cell.SegregationCell.move(), Cell.SugarCell.move(), and Cell.PredPreyCell.pickMove().
int Cell.Cell.futureY protected
Definition at line 26 of file Cell.java.
Referenced by Cell.SugarCell.findHighestSugar(), Cell.SegregationCell.move(), Cell.SugarCell.move(), and Cell.PredPreyCell.pickMove().
Map<String,String> Cell.Cell.myParameters protected
Definition at line 29 of file Cell.java.
Referenced by Cell.SharkCell.breed(), Cell.PredPreyCell.checkBreed(), Cell.PredPreyCell.makeCell(), Cell.SegregationCell.move(), Cell.SugarCell.move(), and Cell.SharkCell.updateStateandMove().
int [] Cell.Cell.xDelta protected
Definition at line 27 of file Cell.java.
Referenced by Cell.SugarCell.assignDeltas(), Cell.LifeCell.setDeltas(), Cell.FireCell.setDeltas(), Cell.SegregationCell.setDeltas(), Cell.SugarCell.setDeltas(), and Cell.PredPreyCell.setDeltas().
int [] Cell.Cell.yDelta protected
Definition at line 28 of file Cell.java.
Referenced by Cell.SugarCell.assignDeltas(), Cell.LifeCell.setDeltas(), Cell.FireCell.setDeltas(), Cell.SegregationCell.setDeltas(), Cell.SugarCell.setDeltas(), and Cell.PredPreyCell.setDeltas().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/Cell/Cell.java