cellsociety_team02: cellsociety_team02.Factory Class Reference
cellsociety_team02.Factory Class Reference
Public Member Functions
Cell makeCell (String s, int r, int c, double state, Map< String, String > params)
Patch makePatch (Cell cell, String myType, int r, int c, double state, Map< String, String > params)
Cell makeRandomCell (String myType, int r, int c, Map< String, String > params, int numStates)
Patch makeRandomPatch (Cell c, String myType, int i, int j, Map< String, String > params, int maxPatch)
Cell makeProbCell (String myType, int r, int c, Map< String, String > paramMap, int numStates, Map< String, String > cellProb)
Patch makeProbPatch (Cell c, String myType, int i, int j, Map< String, String > paramMap, int maxPatch, Map< String, String > patchProb)
Package Attributes
Random rand = new Random()
Detailed Description
Definition at line 17 of file Factory.java.
Member Function Documentation
Cell cellsociety_team02.Factory.makeCell (String s, int r, int c, double state, Map< String, String > params)
Creates a Cell with the appropriate information based on the string of its model type
Parameters
String s is the simulation model\
int r is the row in the array for the current cell
int c is the column in the array for the current cell
Map<String,String> is a map of all parameters for the simulation
Returns
Cell is the cell returned based on the given information
Definition at line 28 of file Factory.java.
References Cell.PredPreyCell.makeCell().
Referenced by cellsociety_team02.XMLParser.doGiven(), cellsociety_team02.Factory.makeProbCell(), cellsociety_team02.Factory.makeRandomCell(), and cellsociety_team02.XMLParser.setNullState().
Patch cellsociety_team02.Factory.makePatch (Cell cell, String myType, int r, int c, double state, Map< String, String > params)
Creates a Patch with the appropriate information based on the string of its model type
Parameters
Cell the cell currently on the patch
String s is the simulation model
int r is the row in the array for the current patch
int c is the column in the array for the current patch
Map<String,String> is a map of all parameters for the simulation
Returns
Patch is the patch returned based on the given information
Definition at line 53 of file Factory.java.
Referenced by cellsociety_team02.XMLParser.doGiven(), cellsociety_team02.Factory.makeProbPatch(), cellsociety_team02.Factory.makeRandomPatch(), and cellsociety_team02.XMLParser.setNullState().
Cell cellsociety_team02.Factory.makeProbCell (String myType, int r, int c, Map< String, String > paramMap, int numStates, Map< String, String > cellProb)
Creates a Cell with state based on the probabilities stored in the cellProb map
Parameters
String myType is the simulation model
int r is the row in the array for the current element
int c is the column in the array for the current element
Map<String,String> is a map of all parameters for the simulation
int numStates is the maximum number of states a cell of this type can have
Map cellProb stores the probabilities for each type of cell
Returns
Cell is the cell returned
Definition at line 99 of file Factory.java.
References cellsociety_team02.Factory.makeCell().
Referenced by cellsociety_team02.XMLParser.doProbability().
Patch cellsociety_team02.Factory.makeProbPatch (Cell c, String myType, int i, int j, Map< String, String > paramMap, int maxPatch, Map< String, String > patchProb)
Creates a Patch based on the probabilites found in the patchProb map
Parameters
Cell the cell currently on the patch
String myType is the simulation model
int r is the row in the array for the current element
int c is the column in the array for the current element
Map<String,String> is a map of all parameters for the simulation
int maxPatch is the maximum number of states a patch of this type can have
Map patchProb stores the probabilities for each type of patch
Returns
Patch is the patch returned
Definition at line 121 of file Factory.java.
References cellsociety_team02.Factory.makePatch().
Referenced by cellsociety_team02.XMLParser.doProbability().
Cell cellsociety_team02.Factory.makeRandomCell (String myType, int r, int c, Map< String, String > params, int numStates)
Creates a random Cell based on the max number of states the cell can have
Parameters
String myType is the simulation model
int r is the row in the array for the current element
int c is the column in the array for the current element
Map<String,String> is a map of all parameters for the simulation
int numStates is the maximum number of states a cell of this type can have
Returns
Cell is the random cell returned
Definition at line 71 of file Factory.java.
References cellsociety_team02.Factory.makeCell().
Referenced by cellsociety_team02.XMLParser.doRandom().
Patch cellsociety_team02.Factory.makeRandomPatch (Cell c, String myType, int i, int j, Map< String, String > params, int maxPatch)
Creates a random Patch based on the max number of states the patch can have
Parameters
Cell the cell currently on the patch
String myType is the simulation model
int r is the row in the array for the current element
int c is the column in the array for the current element
Map<String,String> is a map of all parameters for the simulation
int maxPatch is the maximum number of states a patch of this type can have
Returns
Patch is the random patch returned
Definition at line 85 of file Factory.java.
References cellsociety_team02.Factory.makePatch().
Referenced by cellsociety_team02.XMLParser.doRandom().
Member Data Documentation
Random cellsociety_team02.Factory.rand = new Random() package
Definition at line 18 of file Factory.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/cellsociety_team02/Factory.java