cellsociety_team02: Patch.SugarPatch Class Reference
Patch.SugarPatch Class Reference
Public Member Functions
SugarPatch (Cell c, double state, int x, int y, Map< String, String > params)
void updateState (Patch[][] patches)
Paint getColor ()
Public Member Functions inherited from Patch.Patch
Patch (Cell c, double state, int x, int y, Map< String, String > params)
double getCurrentState ()
double getFutureState ()
Cell getCurrentCell ()
Cell getFutureCell ()
void setFutureCell (Cell c)
int getCurrentY ()
int getCurrentX ()
void setFutureState (double futureState)
abstract void updateState (Patch[][] patches)
abstract Paint getColor ()
void currentToFuture ()
Static Public Attributes
static final int DEFAULT_SUGAR_RATE = 1
static final int DEFAULT_SUGAR_INTERVAL = 1
static final int DEFAULT_MAX_CAPACITY = 4
Private Member Functions
int errorCheck (String string, int result)
Private Attributes
int sugarRate
int sugarInterval
int maxCapacity
int currentTime
Additional Inherited Members
Protected Attributes inherited from Patch.Patch
double currentState
double futureState
int myX
int myY
Cell myCurrentCell
Cell myFutureCell
Map< String, String > myParameters
Detailed Description
Author
Greg Lyons
Chase Malik
Kevin Rhine
SugarPatch implements the abstract Patch class
SugarPatch updates its own state (grows back its sugar) in addition to updating its Cell
The color of the Patch is based on the amount of sugar available
Definition at line 23 of file SugarPatch.java.
Constructor & Destructor Documentation
Patch.SugarPatch.SugarPatch (Cell c, double state, int x, int y, Map< String, String > params)
Definition at line 34 of file SugarPatch.java.
References Patch.SugarPatch.errorCheck().
Member Function Documentation
int Patch.SugarPatch.errorCheck (String string, int result) private
Checks to see if parameter map contains a given value If not, returns a default constant
Parameters
string
result
Returns
int
Definition at line 51 of file SugarPatch.java.
References Patch.Patch.myParameters.
Referenced by Patch.SugarPatch.SugarPatch().
Paint Patch.SugarPatch.getColor ()
Sets the color based on the amount of sugar available Darker = more sugar available
Definition at line 76 of file SugarPatch.java.
References Patch.Patch.currentState.
void Patch.SugarPatch.updateState (Patch patches[][])
Updates both the Patch's state and its Cell's state
Definition at line 61 of file SugarPatch.java.
References Patch.Patch.futureState, Patch.SugarPatch.maxCapacity, Patch.Patch.myCurrentCell, Patch.SugarPatch.sugarRate, and Cell.Cell.updateStateandMove().
Member Data Documentation
int Patch.SugarPatch.currentTime private
Definition at line 28 of file SugarPatch.java.
final int Patch.SugarPatch.DEFAULT_MAX_CAPACITY = 4 static
Definition at line 32 of file SugarPatch.java.
final int Patch.SugarPatch.DEFAULT_SUGAR_INTERVAL = 1 static
Definition at line 31 of file SugarPatch.java.
final int Patch.SugarPatch.DEFAULT_SUGAR_RATE = 1 static
Definition at line 30 of file SugarPatch.java.
int Patch.SugarPatch.maxCapacity private
Definition at line 27 of file SugarPatch.java.
Referenced by Patch.SugarPatch.updateState().
int Patch.SugarPatch.sugarInterval private
Definition at line 26 of file SugarPatch.java.
int Patch.SugarPatch.sugarRate private
Definition at line 25 of file SugarPatch.java.
Referenced by Patch.SugarPatch.updateState().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/Patch/SugarPatch.java