cellsociety_team02: Patch.Patch Class Reference
Patch.Patch Class Reference abstract
Public Member Functions
Patch (Cell c, double state, int x, int y, Map< String, String > params)
double getCurrentState ()
double getFutureState ()
Cell getCurrentCell ()
Cell getFutureCell ()
void setFutureCell (Cell c)
int getCurrentY ()
int getCurrentX ()
void setFutureState (double futureState)
abstract void updateState (Patch[][] patches)
abstract Paint getColor ()
void currentToFuture ()
Protected Attributes
double currentState
double futureState
int myX
int myY
Cell myCurrentCell
Cell myFutureCell
Map< String, String > myParameters
Detailed Description
Author
Greg Lyons
Chase Malik
Kevin Rhine
The Patch class is the basis for the grid Each Patch has its own state, and it holds a Cell that also has its own state
Patches update by checking the grid based on the current state and changing a future state Each Patch updates its given Cell - Cells can manipulate the Patch's futureCell
GridModel loops over the array of Patches and calls each one's updateState method Each of the Patches updates its Cell from within the updateState method
In this sense, the Patches serve as locations for the Cells to inhabit The two objects are able to interact with each other depending on the nature of the simulation
Definition at line 29 of file Patch.java.
Constructor & Destructor Documentation
Patch.Patch.Patch (Cell c, double state, int x, int y, Map< String, String > params)
Definition at line 38 of file Patch.java.
Member Function Documentation
void Patch.Patch.currentToFuture ()
Definition at line 82 of file Patch.java.
Referenced by cellsociety_team02.GridModel.setCurrentToFuture().
abstract Paint Patch.Patch.getColor () abstract
Referenced by cellsociety_team02.GridView.getLocationColor().
Cell Patch.Patch.getCurrentCell ()
Definition at line 56 of file Patch.java.
Referenced by cellsociety_team02.GridModel.changeState(), cellsociety_team02.GridView.makeGrid(), cellsociety_team02.GridModel.numState(), and Cell.SharkCell.updateStateandMove().
double Patch.Patch.getCurrentState ()
Definition at line 48 of file Patch.java.
Referenced by Cell.SugarCell.findHighestSugar(), Cell.SugarCell.move(), and Cell.FireCell.updateStateandMove().
int Patch.Patch.getCurrentX ()
Definition at line 70 of file Patch.java.
Referenced by Cell.SugarCell.findHighestSugar(), Cell.PredPreyCell.pickMove(), and Cell.SharkCell.updateStateandMove().
int Patch.Patch.getCurrentY ()
Definition at line 67 of file Patch.java.
Referenced by Cell.SugarCell.findHighestSugar(), Cell.PredPreyCell.pickMove(), and Cell.SharkCell.updateStateandMove().
Cell Patch.Patch.getFutureCell ()
Definition at line 60 of file Patch.java.
double Patch.Patch.getFutureState ()
Definition at line 52 of file Patch.java.
void Patch.Patch.setFutureCell (Cell c)
Definition at line 63 of file Patch.java.
Referenced by Cell.SharkCell.breed(), Cell.FishCell.breed(), Cell.PredPreyCell.checkBreed(), Cell.SegregationCell.move(), Cell.SugarCell.move(), Cell.LifeCell.updateStateandMove(), Cell.FireCell.updateStateandMove(), Cell.SharkCell.updateStateandMove(), and Cell.FishCell.updateStateandMove().
void Patch.Patch.setFutureState (double futureState)
Definition at line 74 of file Patch.java.
Referenced by Cell.SugarCell.move().
abstract void Patch.Patch.updateState (Patch patches[][]) abstract
Referenced by cellsociety_team02.GridModel.updatePatchesAndCells().
Member Data Documentation
double Patch.Patch.currentState protected
Definition at line 30 of file Patch.java.
Referenced by Patch.FirePatch.getColor(), Patch.SugarPatch.getColor(), and Patch.FirePatch.updateState().
double Patch.Patch.futureState protected
Definition at line 31 of file Patch.java.
Referenced by Patch.FirePatch.updateState(), and Patch.SugarPatch.updateState().
Cell Patch.Patch.myCurrentCell protected
Definition at line 34 of file Patch.java.
Referenced by Patch.GenericPatch.getColor(), Patch.GenericPatch.updateState(), Patch.FirePatch.updateState(), and Patch.SugarPatch.updateState().
Cell Patch.Patch.myFutureCell protected
Definition at line 35 of file Patch.java.
Map<String, String> Patch.Patch.myParameters protected
Definition at line 36 of file Patch.java.
Referenced by Patch.SugarPatch.errorCheck().
int Patch.Patch.myX protected
Definition at line 32 of file Patch.java.
int Patch.Patch.myY protected
Definition at line 33 of file Patch.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/Patch/Patch.java