cellsociety_team02: Cell.SegregationCell Class Reference
Cell.SegregationCell Class Reference
Public Member Functions
SegregationCell (double state, int x, int y, Map< String, String > parameters)
SegregationCell (SegregationCell segregationCell)
void updateStateandMove (Patch[][] patches)
Paint getColor ()
Public Member Functions inherited from Cell.Cell
Cell (double state, int x, int y, Map< String, String > parameters)
Cell (Cell c)
double getCurrentState ()
void setCurrentState (double state)
double getFutureState ()
void setFutureState (double state)
int getFutureX ()
int getFutureY ()
Map< String, String > getParameters ()
abstract void updateStateandMove (Patch[][] patches)
abstract Paint getColor ()
Protected Member Functions
void setDeltas ()
void initialize ()
Protected Member Functions inherited from Cell.Cell
double errorCheck (String string, double result)
abstract void setDeltas ()
abstract void initialize ()
List< Patch > getNeighbors (Patch[][] patches)
Private Member Functions
void move (Patch[][] patches)
Private Attributes
double threshold
Static Private Attributes
static final int empty = 0
static final int stateX = 1
static final int stateY = 2
static final String THRESHOLD = "threshold"
static final double DEFAULT_THRESHOLD = 0.3
Additional Inherited Members
Protected Attributes inherited from Cell.Cell
double currentState
double futureState
int currentX
int currentY
int futureX
int futureY
int[] xDelta
int[] yDelta
Map< String, String > myParameters
String boundaryType
Detailed Description
Definition at line 13 of file SegregationCell.java.
Constructor & Destructor Documentation
Cell.SegregationCell.SegregationCell (double state, int x, int y, Map< String, String > parameters)
Definition at line 22 of file SegregationCell.java.
Referenced by Cell.SegregationCell.move().
Cell.SegregationCell.SegregationCell (SegregationCell segregationCell)
Definition at line 26 of file SegregationCell.java.
Member Function Documentation
Paint Cell.SegregationCell.getColor ()
Definition at line 79 of file SegregationCell.java.
References Cell.Cell.futureState.
void Cell.SegregationCell.initialize () protected
Definition at line 92 of file SegregationCell.java.
References Cell.Cell.errorCheck().
void Cell.SegregationCell.move (Patch patches[][]) private
Moves the current cell to a random empty cell Loops through the list of all patches and finds ones which do not have cells in the future Then it randomly chooses one of these patches and moves there by setting its future cell equal to this and setting this locations current cell equal to an empty cell
Parameters
Patch[][] patches array of all patches on the grid
Definition at line 60 of file SegregationCell.java.
References Cell.Cell.currentX, Cell.Cell.currentY, Cell.Cell.futureX, Cell.Cell.futureY, Cell.Cell.getCurrentState(), Cell.Cell.myParameters, Cell.SegregationCell.SegregationCell(), and Patch.Patch.setFutureCell().
Referenced by Cell.SegregationCell.updateStateandMove().
void Cell.SegregationCell.setDeltas () protected
Definition at line 86 of file SegregationCell.java.
References Cell.Cell.xDelta, and Cell.Cell.yDelta.
void Cell.SegregationCell.updateStateandMove (Patch patches[][])
Definition at line 31 of file SegregationCell.java.
References Cell.Cell.currentState, Cell.Cell.futureState, Cell.Cell.getNeighbors(), Cell.SegregationCell.move(), and Cell.SegregationCell.threshold.
Member Data Documentation
final double Cell.SegregationCell.DEFAULT_THRESHOLD = 0.3 static private
Definition at line 19 of file SegregationCell.java.
final int Cell.SegregationCell.empty = 0 static private
Definition at line 15 of file SegregationCell.java.
final int Cell.SegregationCell.stateX = 1 static private
Definition at line 16 of file SegregationCell.java.
final int Cell.SegregationCell.stateY = 2 static private
Definition at line 17 of file SegregationCell.java.
final String Cell.SegregationCell.THRESHOLD = "threshold" static private
Definition at line 18 of file SegregationCell.java.
double Cell.SegregationCell.threshold private
Definition at line 20 of file SegregationCell.java.
Referenced by Cell.SegregationCell.updateStateandMove().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/Cell/SegregationCell.java