cellsociety_team02: cellsociety_team02.Draw Class Reference
cellsociety_team02.Draw Class Reference
Public Member Functions
Shape drawShape (double height, double width, int i, int j, String type)
Static Public Attributes
static final double GRID_WIDTH = 500
static final double GRID_HEIGHT = 500
Private Member Functions
Shape makeRectangle (double height, double width, int i, int j)
Shape makeHexagon (double height, double width, int i, int j)
Shape makeTriangle (double height, double width, int i, int j)
Polygon makeTriangleRow (int i, int j, double cellWidth, double cellHeight, double offset)
Detailed Description
Definition at line 7 of file Draw.java.
Member Function Documentation
Shape cellsociety_team02.Draw.drawShape (double height, double width, int i, int j, String type)
Creates a shape with appropriate center, height, and width based on the type of grid and the parameters given
Parameters
double height is the height of the array of patches on the grid
double width is the width of the array of patches on the grid
int i is the row in the array for the current element
int j is the column in the array for the current element
String type is the type of grid being made
Returns
Shape is the shape for the (i,j) element in the grid
Definition at line 21 of file Draw.java.
References cellsociety_team02.Draw.makeHexagon(), cellsociety_team02.Draw.makeRectangle(), and cellsociety_team02.Draw.makeTriangle().
Referenced by cellsociety_team02.GridView.makeGrid().
Shape cellsociety_team02.Draw.makeHexagon (double height, double width, int i, int j) private
Definition at line 45 of file Draw.java.
Referenced by cellsociety_team02.Draw.drawShape().
Shape cellsociety_team02.Draw.makeRectangle (double height, double width, int i, int j) private
Creates the rectangle with appropriate height, and width based on the the height and width of the array
Parameters
double height is the height of the array of patches on the grid
double width is the width of the array of patches on the grid
int i is the row in the array for the current element
int j is the column in the array for the current element
Returns
Shape is the rectangle for the (i,j) element in the grid
Definition at line 39 of file Draw.java.
Referenced by cellsociety_team02.Draw.drawShape().
Shape cellsociety_team02.Draw.makeTriangle (double height, double width, int i, int j) private
Creates the triangle with appropriate vertices based on the the height and width of the array
Parameters
double height is the height of the array of patches on the grid
double width is the width of the array of patches on the grid
int i is the row in the array for the current element
int j is the column in the array for the current element
Returns
Shape is the triangle for the (i,j) element in the grid
Definition at line 58 of file Draw.java.
References cellsociety_team02.Draw.makeTriangleRow().
Referenced by cellsociety_team02.Draw.drawShape().
Polygon cellsociety_team02.Draw.makeTriangleRow (int i, int j, double cellWidth, double cellHeight, double offset) private
Creates a triangle with the given offset value
Parameters
double cellHeight is the height of the cell
double cellWidth is the width of the cell
int i is the row in the array for the current element
int j is the column in the array for the current element
double offset value used to line up the even and odd rows properly
Returns
Shape is the triangle for the (i,j) element in the grid
Definition at line 77 of file Draw.java.
Referenced by cellsociety_team02.Draw.makeTriangle().
Member Data Documentation
final double cellsociety_team02.Draw.GRID_HEIGHT = 500 static
Definition at line 9 of file Draw.java.
final double cellsociety_team02.Draw.GRID_WIDTH = 500 static
Definition at line 8 of file Draw.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/cellsociety_team02/Draw.java