cellsociety_team02: cellsociety_team02.GridView Class Reference
cellsociety_team02.GridView Class Reference
Public Member Functions
GridView (GridModel model, String language)
void initialize ()
Scene getScene ()
KeyFrame startHandler (double interval)
void updateSpeed (double value)
void step ()
Static Public Attributes
static final Dimension DEFAULT_SIZE = new Dimension(600, 700)
static final int GRAPH_WIDTH = 600
static final int GRAPH_HEIGHT = 150
static final int AXIS_WIDTH = 50
static final int GRAPH_INTERVAL =2
static final String DEFAULT_RESOURCE_PACKAGE = "resources/"
Protected Member Functions
void playPause ()
Private Member Functions
Node makeButtons ()
Slider setUpSpeedSlider ()
void load ()
Button makeButton (String property, EventHandler< ActionEvent > handler)
Node makeGraph ()
void startAnimation ()
Node makeGrid ()
Paint getLocationColor (Patch p, Cell c)
Private Attributes
Scene myScene
ResourceBundle myResources
GridModel myModel
Timeline myAnimation
double myInterval
List< Shape > myShapeList
BorderPane root
boolean isRunning
String gridType
int numFrames =0
NumberAxis xAxis = new NumberAxis()
NumberAxis yAxis = new NumberAxis()
LineChart< Number, Number > popChart
Static Private Attributes
static final double MIN_INTERVAL = 0.1
static final double MAX_INTERVAL = 2.2
static final double INITIAL_INTERVAL = 1.0
Detailed Description
Definition at line 35 of file GridView.java.
Constructor & Destructor Documentation
cellsociety_team02.GridView.GridView (GridModel model, String language)
Sets up the initial viewer Initializes certain values and loads the resource bundle Then calls load to prompt the user for a file and create the scene
Parameters
model GridModel being manipulated
String language of the resource package
Definition at line 68 of file GridView.java.
References cellsociety_team02.GridView.INITIAL_INTERVAL, cellsociety_team02.GridView.initialize(), and cellsociety_team02.GridView.load().
Member Function Documentation
Paint cellsociety_team02.GridView.getLocationColor (Patch p, Cell c) private
Gets the grid location's color based on the patch and cell at the location
Parameters
Patch p at the location
Cell c at the location
Returns
Paint color of the grid location
Definition at line 294 of file GridView.java.
References Patch.Patch.getColor(), and Cell.Cell.getColor().
Referenced by cellsociety_team02.GridView.makeGrid().
Scene cellsociety_team02.GridView.getScene ()
Returns myScene
Returns
Scene current scene
Definition at line 194 of file GridView.java.
References cellsociety_team02.GridView.myScene.
Referenced by cellsociety_team02.Main.start().
void cellsociety_team02.GridView.initialize ()
Sets up the initial scene
Definition at line 184 of file GridView.java.
References cellsociety_team02.GridView.makeButtons().
Referenced by cellsociety_team02.GridView.GridView().
void cellsociety_team02.GridView.load () private
Action to occur when the Load button is pushed Stops the current animation and prompts the user for a new simulation
Definition at line 142 of file GridView.java.
References cellsociety_team02.GridModel.getGridType(), cellsociety_team02.GridModel.load(), cellsociety_team02.GridView.makeGraph(), and cellsociety_team02.GridView.makeGrid().
Referenced by cellsociety_team02.GridView.GridView(), and cellsociety_team02.GridView.makeButtons().
Button cellsociety_team02.GridView.makeButton (String property, EventHandler< ActionEvent > handler) private
Makes a button with a particular name in the resource file and a particular EventHandler
Parameters
String property name in the resource file
EventHandler handler for the new button
Returns
Button with the appropriate label and handler
Definition at line 156 of file GridView.java.
Referenced by cellsociety_team02.GridView.makeButtons().
Node cellsociety_team02.GridView.makeButtons () private
Creates all of the necessary buttons Play/Pause,Load,Step,Speed Slider
Definition at line 84 of file GridView.java.
References cellsociety_team02.GridView.load(), cellsociety_team02.GridView.makeButton(), cellsociety_team02.GridView.playPause(), cellsociety_team02.GridView.setUpSpeedSlider(), and cellsociety_team02.GridView.step().
Referenced by cellsociety_team02.GridView.initialize().
Node cellsociety_team02.GridView.makeGraph () private
Makes the graph
Returns
Node containing the graph
Definition at line 166 of file GridView.java.
References cellsociety_team02.GridModel.addData(), and cellsociety_team02.GridView.popChart.
Referenced by cellsociety_team02.GridView.load(), and cellsociety_team02.GridView.step().
Node cellsociety_team02.GridView.makeGrid () private
Makes the graphical display for the grid Loops through all of the patches and creates a new shape for each one based on its cell Creates a handler for each of these shapes, so that the user can interact with the simulation
We are still having issues with updating individual states based on user input There is a preliminary implementation in place (commented out) but it runs into issues with scope Code can still compile and run without handler commented out, but we did so to avoid any errors in the program
Definition at line 259 of file GridView.java.
References cellsociety_team02.Draw.drawShape(), Patch.Patch.getCurrentCell(), cellsociety_team02.GridView.getLocationColor(), and cellsociety_team02.GridModel.getPatches().
Referenced by cellsociety_team02.GridView.load(), and cellsociety_team02.GridView.step().
void cellsociety_team02.GridView.playPause () protected
Action to occur when the Play/Pause button is pushed Changes whether or not the simulation is running
Definition at line 134 of file GridView.java.
References cellsociety_team02.GridView.isRunning, and cellsociety_team02.GridView.startAnimation().
Referenced by cellsociety_team02.GridView.makeButtons().
Slider cellsociety_team02.GridView.setUpSpeedSlider () private
Creates the slider to define the speed of the simulations
Definition at line 116 of file GridView.java.
References cellsociety_team02.GridView.updateSpeed().
Referenced by cellsociety_team02.GridView.makeButtons().
void cellsociety_team02.GridView.startAnimation () private
Starts the Timeline with the current value of myInterval
Definition at line 201 of file GridView.java.
References cellsociety_team02.GridView.startHandler().
Referenced by cellsociety_team02.GridView.playPause(), and cellsociety_team02.GridView.updateSpeed().
KeyFrame cellsociety_team02.GridView.startHandler (double interval)
Creates a new key frame every interval that either steps or does nothing based on the isRunning variable
Parameters
interval the interval between new key frames
Returns
KeyFrame frame of information
Definition at line 215 of file GridView.java.
References cellsociety_team02.GridView.step().
Referenced by cellsociety_team02.GridView.startAnimation().
void cellsociety_team02.GridView.step ()
Performs one tick in the simulation Displays the grid for the new tick updates the graph every GRAPH_INTERVAL ticks
Definition at line 242 of file GridView.java.
References cellsociety_team02.GridView.makeGraph(), cellsociety_team02.GridView.makeGrid(), and cellsociety_team02.GridModel.update().
Referenced by cellsociety_team02.GridView.makeButtons(), and cellsociety_team02.GridView.startHandler().
void cellsociety_team02.GridView.updateSpeed (double value)
Updates the speed of the animation based on the parameter Starts the Timeline
Parameters
value new interval value
Definition at line 232 of file GridView.java.
References cellsociety_team02.GridView.startAnimation().
Referenced by cellsociety_team02.GridView.setUpSpeedSlider().
Member Data Documentation
final int cellsociety_team02.GridView.AXIS_WIDTH = 50 static
Definition at line 41 of file GridView.java.
final String cellsociety_team02.GridView.DEFAULT_RESOURCE_PACKAGE = "resources/" static
Definition at line 43 of file GridView.java.
final Dimension cellsociety_team02.GridView.DEFAULT_SIZE = new Dimension(600, 700) static
Definition at line 38 of file GridView.java.
final int cellsociety_team02.GridView.GRAPH_HEIGHT = 150 static
Definition at line 40 of file GridView.java.
final int cellsociety_team02.GridView.GRAPH_INTERVAL =2 static
Definition at line 42 of file GridView.java.
final int cellsociety_team02.GridView.GRAPH_WIDTH = 600 static
Definition at line 39 of file GridView.java.
String cellsociety_team02.GridView.gridType private
Definition at line 55 of file GridView.java.
final double cellsociety_team02.GridView.INITIAL_INTERVAL = 1.0 static private
Definition at line 47 of file GridView.java.
Referenced by cellsociety_team02.GridView.GridView().
boolean cellsociety_team02.GridView.isRunning private
Definition at line 54 of file GridView.java.
Referenced by cellsociety_team02.GridView.playPause().
final double cellsociety_team02.GridView.MAX_INTERVAL = 2.2 static private
Definition at line 46 of file GridView.java.
final double cellsociety_team02.GridView.MIN_INTERVAL = 0.1 static private
Definition at line 45 of file GridView.java.
Timeline cellsociety_team02.GridView.myAnimation private
Definition at line 50 of file GridView.java.
double cellsociety_team02.GridView.myInterval private
Definition at line 51 of file GridView.java.
GridModel cellsociety_team02.GridView.myModel private
Definition at line 49 of file GridView.java.
ResourceBundle cellsociety_team02.GridView.myResources private
Definition at line 48 of file GridView.java.
Scene cellsociety_team02.GridView.myScene private
Definition at line 37 of file GridView.java.
Referenced by cellsociety_team02.GridView.getScene().
List<Shape> cellsociety_team02.GridView.myShapeList private
Definition at line 52 of file GridView.java.
int cellsociety_team02.GridView.numFrames =0 private
Definition at line 56 of file GridView.java.
LineChart<Number,Number> cellsociety_team02.GridView.popChart private
Definition at line 59 of file GridView.java.
Referenced by cellsociety_team02.GridView.makeGraph().
BorderPane cellsociety_team02.GridView.root private
Definition at line 53 of file GridView.java.
NumberAxis cellsociety_team02.GridView.xAxis = new NumberAxis() private
Definition at line 57 of file GridView.java.
NumberAxis cellsociety_team02.GridView.yAxis = new NumberAxis() private
Definition at line 58 of file GridView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/cellsociety_team02/GridView.java