cellsociety_team02: Cell.FireCell Class Reference
Cell.FireCell Class Reference
Public Member Functions
FireCell (double state, int x, int y, Map< String, String > parameters)
FireCell (FireCell fireCell)
void updateStateandMove (Patch[][] patches)
Paint getColor ()
Public Member Functions inherited from Cell.Cell
Cell (double state, int x, int y, Map< String, String > parameters)
Cell (Cell c)
double getCurrentState ()
void setCurrentState (double state)
double getFutureState ()
void setFutureState (double state)
int getFutureX ()
int getFutureY ()
Map< String, String > getParameters ()
abstract void updateStateandMove (Patch[][] patches)
abstract Paint getColor ()
Protected Member Functions
void setDeltas ()
void initialize ()
Protected Member Functions inherited from Cell.Cell
double errorCheck (String string, double result)
abstract void setDeltas ()
abstract void initialize ()
List< Patch > getNeighbors (Patch[][] patches)
Package Attributes
double probCatch
Private Member Functions
boolean burningNeighbor (List< Patch > neighbors)
Static Private Attributes
static final int burning = 1
static final int notBurning = 0
static final double DEFAULT_CATCH = 0.3
Additional Inherited Members
Protected Attributes inherited from Cell.Cell
double currentState
double futureState
int currentX
int currentY
int futureX
int futureY
int[] xDelta
int[] yDelta
Map< String, String > myParameters
String boundaryType
Detailed Description
Definition at line 10 of file FireCell.java.
Constructor & Destructor Documentation
Cell.FireCell.FireCell (double state, int x, int y, Map< String, String > parameters)
Definition at line 17 of file FireCell.java.
Referenced by Cell.FireCell.updateStateandMove().
Cell.FireCell.FireCell (FireCell fireCell)
Definition at line 21 of file FireCell.java.
Member Function Documentation
boolean Cell.FireCell.burningNeighbor (List< Patch > neighbors) private
Loops through the list of neighboring patches If one of them contains a burning cell then return true
Parameters
List<Patch> neighboring patches to the current cell
Returns
boolean returns true if the cell has a burning neighbor
Definition at line 52 of file FireCell.java.
References Cell.FireCell.burning.
Referenced by Cell.FireCell.updateStateandMove().
Paint Cell.FireCell.getColor ()
Definition at line 61 of file FireCell.java.
References Cell.Cell.currentState.
void Cell.FireCell.initialize () protected
Definition at line 75 of file FireCell.java.
References Cell.Cell.errorCheck().
void Cell.FireCell.setDeltas () protected
Definition at line 68 of file FireCell.java.
References Cell.Cell.xDelta, and Cell.Cell.yDelta.
void Cell.FireCell.updateStateandMove (Patch patches[][])
Cell's logic for the fire spreading simulation
Parameters
Patch[][] patches on the grid
Definition at line 30 of file FireCell.java.
References Cell.FireCell.burning, Cell.FireCell.burningNeighbor(), Cell.Cell.currentState, Cell.Cell.currentX, Cell.Cell.currentY, Cell.FireCell.FireCell(), Cell.Cell.futureState, Patch.Patch.getCurrentState(), Cell.Cell.getNeighbors(), Cell.FireCell.notBurning, and Patch.Patch.setFutureCell().
Member Data Documentation
final int Cell.FireCell.burning = 1 static private
Definition at line 13 of file FireCell.java.
Referenced by Cell.FireCell.burningNeighbor(), and Cell.FireCell.updateStateandMove().
final double Cell.FireCell.DEFAULT_CATCH = 0.3 static private
Definition at line 15 of file FireCell.java.
final int Cell.FireCell.notBurning = 0 static private
Definition at line 14 of file FireCell.java.
Referenced by Cell.FireCell.updateStateandMove().
double Cell.FireCell.probCatch package
Definition at line 12 of file FireCell.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/Cell/FireCell.java