cellsociety_team02: Cell.LifeCell Class Reference
Cell.LifeCell Class Reference
Public Member Functions
LifeCell (double state, int x, int y, Map< String, String > parameters)
LifeCell (LifeCell lifeCell)
void updateStateandMove (Patch[][] patches)
Color getColor ()
Public Member Functions inherited from Cell.Cell
Cell (double state, int x, int y, Map< String, String > parameters)
Cell (Cell c)
double getCurrentState ()
void setCurrentState (double state)
double getFutureState ()
void setFutureState (double state)
int getFutureX ()
int getFutureY ()
Map< String, String > getParameters ()
abstract void updateStateandMove (Patch[][] patches)
abstract Paint getColor ()
Protected Member Functions
void setDeltas ()
void initialize ()
Protected Member Functions inherited from Cell.Cell
double errorCheck (String string, double result)
abstract void setDeltas ()
abstract void initialize ()
List< Patch > getNeighbors (Patch[][] patches)
Private Member Functions
int aliveNeighbors (List< Patch > neighborsList)
Static Private Attributes
static final int alive = 1
static final int dead = 0
Additional Inherited Members
Protected Attributes inherited from Cell.Cell
double currentState
double futureState
int currentX
int currentY
int futureX
int futureY
int[] xDelta
int[] yDelta
Map< String, String > myParameters
String boundaryType
Detailed Description
Definition at line 10 of file LifeCell.java.
Constructor & Destructor Documentation
Cell.LifeCell.LifeCell (double state, int x, int y, Map< String, String > parameters)
Definition at line 15 of file LifeCell.java.
Referenced by Cell.LifeCell.updateStateandMove().
Cell.LifeCell.LifeCell (LifeCell lifeCell)
Definition at line 19 of file LifeCell.java.
Member Function Documentation
int Cell.LifeCell.aliveNeighbors (List< Patch > neighborsList) private
Loops through the list of neighboring patches Returns the number of live neighbors
Parameters
List<Patch> neighboring patches to the current cell
Returns
int returns the number of live neighbors
Definition at line 47 of file LifeCell.java.
References Cell.LifeCell.alive.
Referenced by Cell.LifeCell.updateStateandMove().
Color Cell.LifeCell.getColor ()
Definition at line 57 of file LifeCell.java.
References Cell.Cell.futureState.
void Cell.LifeCell.initialize () protected
Definition at line 71 of file LifeCell.java.
void Cell.LifeCell.setDeltas () protected
Definition at line 65 of file LifeCell.java.
References Cell.Cell.xDelta, and Cell.Cell.yDelta.
void Cell.LifeCell.updateStateandMove (Patch patches[][])
Definition at line 24 of file LifeCell.java.
References Cell.LifeCell.alive, Cell.LifeCell.aliveNeighbors(), Cell.Cell.currentState, Cell.Cell.currentX, Cell.Cell.currentY, Cell.LifeCell.dead, Cell.Cell.futureState, Cell.Cell.getNeighbors(), Cell.LifeCell.LifeCell(), and Patch.Patch.setFutureCell().
Member Data Documentation
final int Cell.LifeCell.alive = 1 static private
Definition at line 12 of file LifeCell.java.
Referenced by Cell.LifeCell.aliveNeighbors(), and Cell.LifeCell.updateStateandMove().
final int Cell.LifeCell.dead = 0 static private
Definition at line 13 of file LifeCell.java.
Referenced by Cell.LifeCell.updateStateandMove().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/cellsociety_team02/repository/src/Cell/LifeCell.java